quarkus:
  datasource:
    db-kind: mssql
    jdbc:
      url: jdbc:sqlserver://;serverName=localhost;databaseName=mkplatlocal;encrypt=true;trustServerCertificate=true;
      max-size: 200
  http:
    port: 8081
    root-path: /account
  rest-client:
    platform-api:
    catalog-api:
      url: "http://localhost:8083/catalog"
      verify-host: false
  hibernate-orm:
    log:
      sql: false
  swagger-ui:
    path: /account/swagger-ui
    enable: true
    always-include: true
